name: Run non-interactive demo

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  readme:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run the README code parts
        run: bin/test-readme
