name: Run non-interactive demo

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  readme:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run the README code parts
        run: bin/test-readme
  tiptoe:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone sdk
        run: |
          mkdir dfn
          cd dfn
          git clone https://github.com/dfinity/sdk.git
          cd sdk
          for branch in ic-nns-install-part2 ; do
            git worktree add "branches/$branch" "$branch"
            echo "${branch}_commit=$(git )"
          done
      - name: Get cached sdk-nns-install binary
        id: sdk_nns_install_cache
        uses: actions/cache@v2
        with:
          path: |
            $PWD/dfn/sdk/branches/ic-nns-install-part2/target/debug/
          key: "dfx-${{ env.IC_COMMIT }}-v001"

      - name: Install sdk-nns-install binary
        if: steps.sdk_nns_install_cache.outputs.cache-hit != 'true'
        run: |
            cd $PWD/dfn/sdk/branches/ic-nns-install-part2
            cargo build

      - name: Install sdk
        run: |
          mkdir -p bin
          cp dfn/sdk/branches/ic-nns-install-part2/target/debug/dfx bin/dfx
          echo $PWD/bin/ >>> $GITHUB_ENV

#
#       - name: Set path
#         run: |
#           echo $PWD/dfn/sdk/branches/ic-nns-install-part2/target/debug/ >>> $GITHUB_ENV
#           echo $PWD/bin/ >>> $GITHUB_ENV
#
#       - name: Set up environment variables
#         run: cp .demo-init-local .demo-env
#
#       - name: Start dfx server
#         run: dfx start --clean --background
#       - name: Install NNS
#         run: dfx nns install
